Repository TeamProject10Final/TeamProject_Final, pull requests merged in 2024-07, with the labels that each got.

#120 Feat/verified email
  app/src/main/java/com/nomorelateness/donotlate/AppContainer.kt
  app/src/main/java/com/nomorelateness/donotlate/MainActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/MainViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/core/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/nomorelateness/donotlate/core/domain/repository/UserRepository.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/domain/repository/AuthRepository.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/domain/useCase/CheckUserEmailVerificationUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/domain/useCase/DeleteUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/domain/useCase/SendEmailVerificationUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/LogInViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/SignUpViewmodel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/SignupFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/setting/domain/usecase/DeleteUserUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/setting/presentation/view/SettingFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/setting/presentation/view/SettingsViewModel.kt
  app/src/main/res/layout/fragment_my_promise_room.xml
Labels: enhancement, fix

#122 Feat/verified email
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/SignupFragment.kt
Labels: fix

#123 Feature/tutorial
  .idea/misc.xml
  app/src/main/java/com/nomorelateness/donotlate/MainActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/CalculationActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/ConsumptionActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/directionRoute/presentation/DirectionRouteActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/searchPlace/presentation/search/PlaceSearchFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/setting/presentation/view/SettingFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/tutorial/TutorialImageAdapter.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/tutorial/TutorialViewPagerFragment.kt
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ic_email.png
  app/src/main/res/drawable/tutorial_1.png
  app/src/main/res/drawable/tutorial_2.png
  app/src/main/res/drawable/tutorial_3.png
  app/src/main/res/drawable/tutorial_4.png
  app/src/main/res/drawable/tutorial_5.png
  app/src/main/res/drawable/tutorial_6.png
  app/src/main/res/drawable/tutorial_7.png
  app/src/main/res/drawable/tutorial_8.png
  app/src/main/res/layout/fragment_calculation2.xml
  app/src/main/res/layout/fragment_email_confirm_dialog.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_room_start.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/fragment_tutorial_view_pager.xml
  app/src/main/res/layout/item_tutorial.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#124 Temp/keys
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nomorelateness/donotlate/MainActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/adapter/MyPromiseAdapter.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseListFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseListViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/widget/SharedPreferenceHelper.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/widget/WidgetProvider.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/widget/WidgetShared.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/widget/viewmodel/WidgetViewModel.kt
  app/src/main/res/layout/widget_layout.xml
  app/src/main/res/xml/widget_info.xml
  gradle/libs.versions.toml
Labels: enhancement, help wanted

#125 Feat/verified email
  app/src/main/java/com/nomorelateness/donotlate/AppContainer.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/SignUpViewmodel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/SignupFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/data/database/FirebaseConsumptionDTO.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/data/database/RoomDao.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/data/database/RoomEntity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/data/repository/ConsumptionRepositoryImpl.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/data/repository/ConsumptionRepositoryImpl2.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/entity/ConsumptionEntity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/entity/FirebaseConsumptionEntity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/repository/ConsumptionRepository.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/repository/ConsumptionRepository2.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/usecase/ClearAllConsumptionsUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/usecase/ConsumptionDataSyncUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/usecase/DeleteConsumptionDataFromFirebaseUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/usecase/InsertConsumptionDataToFirebaseUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/usecase/InsertConsumptionUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/domain/usecase/UpdateFinishedFromFirebaseUseCase.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/CalculationActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/CalculationFragment1.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/CalculationFragment2.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/CalculationFragment3.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/ConsumptionActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/ConsumptionModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/ConsumptionViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/FirebaseConsumptionModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/Mapper.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/consumption/presentation/SharedViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/setting/presentation/view/SettingFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/setting/presentation/view/SettingsViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/setting/presentation/view/dialog/LoadingDialog.kt
  app/src/main/res/layout/fragment_my_promise_room.xml
Labels: enhancement

#128 Temp/keys user
  app/src/main/java/com/nomorelateness/donotlate/AppContainer.kt
  app/src/main/java/com/nomorelateness/donotlate/MainActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/directionRoute/presentation/DirectionsViewModel1.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/main/presentation/view/MainFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseListFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/widget/SharedPreferenceHelper.kt
Labels: enhancement, fix

#129 fix: 위젯 크기 수정, MainActivity 위 위젯 재클릭 시의 문제 해결
  app/src/main/java/com/nomorelateness/donotlate/MainActivity.kt
  app/src/main/res/xml/widget_info.xml
Labels: fix

#130 add ui수정
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26__3_43__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher-playstore.png
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher1.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher2.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher3.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher4.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground1.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground2.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground3.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground4.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round1.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round2.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round3.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round4.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/shelved.patch
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseListFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/room/presentation/dialog/RoomDateDialog.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/setting/presentation/view/question/SettingChatFragment.kt
  app/src/main/res/layout/fragment_my_promise_room.xml
  app/src/main/res/layout/fragment_mypromise_list.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#131 fix 약속 잡기 ViewPagerFragment 수정했습니다.
  .idea/git_toolbox_blame.xml
  app/src/main/java/com/nomorelateness/donotlate/feature/room/presentation/dialog/CancelFragmentDialog.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/room/presentation/view/RoomMapFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/room/presentation/view/RoomResultFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/room/presentation/view/RoomStartFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/room/presentation/view/RoomViewModel.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/room/presentation/view/ViewPagerFragment.kt
Labels: fix

#132 temp/widgetToast 위젯 설정 시 토스트메시지
  app/src/main/java/com/nomorelateness/donotlate/feature/mypromise/presentation/view/MyPromiseListFragment.kt
Labels: enhancement

#133 fix 버그 수정(24.07.04)
  .idea/git_toolbox_prj.xml
  app/src/main/java/com/nomorelateness/donotlate/MainActivity.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/nomorelateness/donotlate/feature/main/presentation/view/MainFragment.kt
Labels: fix
