Repository TeamProject10Final/TeamProject_Final, pull requests merged in 2024-06, with the labels that each got.

#48 로그인 -> 로그아웃 처리
  .idea/misc.xml
  app/src/main/java/com/example/donotlate/AppContainer.kt
  app/src/main/java/com/example/donotlate/MainActivity.kt
  app/src/main/java/com/example/donotlate/MainViewModel.kt
  app/src/main/java/com/example/donotlate/core/data/session/SessionManagerImpl.kt
  app/src/main/java/com/example/donotlate/core/domain/session/SessionManager.kt
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/example/donotlate/feature/auth/presentation/viewmodel/LogInViewModel.kt
  app/src/main/java/com/example/donotlate/feature/main/presentation/view/MainFragment.kt
  app/src/main/java/com/example/donotlate/feature/main/presentation/view/MainPageViewModel.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/dialog/LogoutFragmentDialog.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/MyPageFragment.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/SettingFragment.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/SettingsViewModel.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/viewmodel/SettingViewModel.kt
  app/src/main/res/layout/fragment_login.xml
Labels: enhancement

#75 Fix/view touch error
  .idea/shelf/Uncommitted_changes_before_Update_at_6_21_24,_15_39_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Update_at_6_23_24,_02_36_[Changes]/shelved.patch
  app/src/main/java/com/example/donotlate/AppContainer.kt
  app/src/main/java/com/example/donotlate/core/data/mapper/FriendRequestMapper.kt
  app/src/main/java/com/example/donotlate/core/data/repository/FirebaseDataSourceImpl.kt
  app/src/main/java/com/example/donotlate/core/data/repository/PromiseRoomRepositoryImpl.kt
  app/src/main/java/com/example/donotlate/core/data/response/FriendRequestDTO.kt
  app/src/main/java/com/example/donotlate/core/domain/model/FriendRequestEntity.kt
  app/src/main/java/com/example/donotlate/core/domain/repository/FirebaseDataRepository.kt
  app/src/main/java/com/example/donotlate/core/domain/repository/PromiseRoomRepository.kt
  app/src/main/java/com/example/donotlate/core/domain/usecase/promiseusecase/RemoveParticipantsUseCase.kt
  app/src/main/java/com/example/donotlate/core/util/UtilityKeyboard.kt
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/SignupFragment.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/CalculationFragment1.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/CalculationFragment2.kt
  app/src/main/java/com/example/donotlate/feature/friends/data/mapper/Mapper.kt
  app/src/main/java/com/example/donotlate/feature/friends/data/model/FriendRequestDTO.kt
  app/src/main/java/com/example/donotlate/feature/friends/data/repository/FriendRequestRepositoryImpl.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/mapper/Mapper.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/model/FriendRequestModel.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/view/FriendsAcceptDialogFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/model/PromiseModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonDialog.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonSelectionDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomFriendFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomMapFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomResultFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomStartFragment.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/presentation/search/PlaceSearchFragment.kt
  app/src/main/res/layout/dialog_radiobutton.xml
  app/src/main/res/layout/fragment_my_promise_room.xml
Labels: fix

#76 add bottom sheet 변경
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/DirectionsDialogFragment.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/MapFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomMapFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomStartFragment.kt
  app/src/main/res/drawable/item_bottomsheet.xml
  app/src/main/res/layout/fragment_directions_bottom.xml
  app/src/main/res/layout/fragment_directions_dialog.xml
  app/src/main/res/layout/fragment_information_dialog.xml
  app/src/main/res/layout/fragment_my_promise_room.xml
  app/src/main/res/layout/fragment_room_map_bottom.xml
  app/src/main/res/layout/fragment_route_details.xml
Labels: enhancement

#77 Temp/chat room location
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/SignupFragment.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/CalculationFragment1.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/CalculationFragment2.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/CalculationFragment3.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/ConsumptionActivity.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/ConsumptionViewModel.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/SharedViewModel.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/DirectionsViewModel1.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/MapFragment.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/view/FriendsRequestFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomFriendFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomMapFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomStartFragment.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/presentation/search/PlaceSearchFragment.kt
  app/src/main/res/drawable/btn_info_round_gray.xml
  app/src/main/res/layout/activity_consumption.xml
  app/src/main/res/layout/dialog_radiobutton_selection.xml
  app/src/main/res/layout/fragment_calculation2.xml
Labels: enhancement, fix

#78 fix: viewpager
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/ViewPagerFragment.kt
Labels: fix

#79 add dialog 수정 , scroll view 추가
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonDialog.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonSelectionDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/dialog/RoomDateDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/dialog/RoomTimeDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomStartFragment.kt
  app/src/main/res/drawable/item_date_dialog.xml
  app/src/main/res/layout/activity_consumption.xml
  app/src/main/res/layout/back_dialog.xml
  app/src/main/res/layout/dialog_radiobutton.xml
  app/src/main/res/layout/dialog_radiobutton_selection.xml
  app/src/main/res/layout/fragment_accept_dialog.xml
  app/src/main/res/layout/fragment_calculation1.xml
  app/src/main/res/layout/fragment_calculation2.xml
  app/src/main/res/layout/fragment_calculation3.xml
  app/src/main/res/layout/fragment_chat_room_list.xml
  app/src/main/res/layout/fragment_friends.xml
  app/src/main/res/layout/fragment_friends_request.xml
  app/src/main/res/layout/fragment_friends_request_list.xml
  app/src/main/res/layout/fragment_information_dialog.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_mini_game.xml
  app/src/main/res/layout/fragment_my_promise_room.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_room_date_dialog.xml
  app/src/main/res/layout/fragment_room_friend.xml
  app/src/main/res/layout/fragment_room_map.xml
  app/src/main/res/layout/fragment_room_result.xml
  app/src/main/res/layout/fragment_room_start.xml
  app/src/main/res/layout/fragment_room_time_dialog.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/fragment_setting_chat.xml
  app/src/main/res/layout/fragment_setting_email.xml
  app/src/main/res/layout/fragment_setting_information.xml
  app/src/main/res/layout/fragment_setting_information_personal.xml
  app/src/main/res/layout/fragment_setting_license.xml
  app/src/main/res/layout/fragment_setting_location_agreement.xml
  app/src/main/res/layout/fragment_setting_personal_agreement.xml
  app/src/main/res/layout/fragment_setting_question.xml
  app/src/main/res/layout/fragment_setting_service.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/item_rv_my_promise.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: enhancement

#80 add dialog 수정
  app/src/main/java/com/example/donotlate/feature/room/presentation/dialog/RoomTimeDialog.kt
Labels: fix

#81 Feat/check arrived
  app/src/main/java/com/example/donotlate/AppContainer.kt
  app/src/main/java/com/example/donotlate/core/data/mapper/PromiseRoomMapper.kt
  app/src/main/java/com/example/donotlate/core/data/repository/FirebaseDataSourceImpl.kt
  app/src/main/java/com/example/donotlate/core/data/response/PromiseRoomResponse.kt
  app/src/main/java/com/example/donotlate/core/domain/model/PromiseRoomEntity.kt
  app/src/main/java/com/example/donotlate/core/domain/repository/FirebaseDataRepository.kt
  app/src/main/java/com/example/donotlate/core/util/UtilityKeyboard.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/domain/usecase/UpdateArrivalStatusUseCase.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/adapter/MyPromiseAdapter.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/mapper/mapper.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/model/PromiseModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseListViewModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonDialog.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonSelectionDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/mapper/Mapper.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/model/PromiseRoomModel.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomMapFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomResultFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomViewModel.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/ViewPagerFragment.kt
Labels: enhancement

#83 fix : 시간 파싱 오류 해결
  app/src/main/java/com/example/donotlate/core/util/util.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/model/PromiseModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseListViewModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomStartFragment.kt
Labels: fix

#84 Temp/chat room location
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
Labels: fix

#91 Add & Fix, feat/deleteUser -> dev
  .idea/misc.xml
  app/src/main/java/com/example/donotlate/AppContainer.kt
  app/src/main/java/com/example/donotlate/core/data/mapper/PromiseRoomMapper.kt
  app/src/main/java/com/example/donotlate/core/data/repository/FirebaseDataSourceImpl.kt
  app/src/main/java/com/example/donotlate/core/data/response/PromiseRoomResponse.kt
  app/src/main/java/com/example/donotlate/core/domain/model/PromiseRoomEntity.kt
  app/src/main/java/com/example/donotlate/core/domain/repository/FirebaseDataRepository.kt
  app/src/main/java/com/example/donotlate/feature/auth/data/model/RegisterUserDTO.kt
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/view/FriendsAcceptDialogFragment.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/view/FriendsFragment.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/view/FriendsRequestDialogFragment.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/view/FriendsRequestFragment.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/view/FriendsRequestListFragment.kt
  app/src/main/java/com/example/donotlate/feature/friends/presentation/view/FriendsViewModel.kt
  app/src/main/java/com/example/donotlate/feature/main/presentation/mapper/Mapper.kt
  app/src/main/java/com/example/donotlate/feature/main/presentation/model/ChatRoomModel.kt
  app/src/main/java/com/example/donotlate/feature/main/presentation/view/MainFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/domain/usecase/UpdateDepartureStatusUseCase.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/mapper/mapper.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/model/PromiseModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonDialog.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonSelectionDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/mapper/Mapper.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/model/PromiseRoomModel.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomFriendFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomResultFragment.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/SettingFragment.kt
Labels: enhancement, fix

#94 Feat/delete user
  app/src/main/java/com/example/donotlate/AppContainer.kt
  app/src/main/java/com/example/donotlate/core/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/example/donotlate/core/domain/repository/UserRepository.kt
  app/src/main/java/com/example/donotlate/feature/main/presentation/model/Result.kt
  app/src/main/java/com/example/donotlate/feature/setting/domain/usecase/DeleteUserUseCase.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/SettingFragment.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/SettingsViewModel.kt
  app/src/main/res/layout/fragment_setting.xml
Labels: enhancement

#95 fix/나머지 string 작업 및 EN.ver 텍스트 겹침 해결
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/LoginFragment.kt
  app/src/main/java/com/example/donotlate/feature/auth/presentation/view/SignupFragment.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/CalculationFragment2.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/CalculationFragment3.kt
  app/src/main/java/com/example/donotlate/feature/minigame/BottomSheetDialogFragment.kt
  app/src/main/java/com/example/donotlate/feature/minigame/RouletteViewModel.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/dialog/CancelFragmentDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/dialog/LogoutFragmentDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/dialog/ResultFragmentDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomFriendFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomMapFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomResultFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomStartFragment.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/presentation/detail/PlaceDetailFragment.kt
  app/src/main/res/layout/activity_consumption.xml
  app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_calculation1.xml
  app/src/main/res/layout/fragment_calculation2.xml
  app/src/main/res/layout/fragment_information_dialog.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_room_friend.xml
  app/src/main/res/layout/fragment_room_map.xml
  app/src/main/res/layout/fragment_room_start.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/consumptionCategory.xml
  app/src/main/res/values/strings.xml
Labels: fix

#98 Temp/merge dialog
  app/src/main/java/com/example/donotlate/core/data/repository/FirebaseDataSourceImpl.kt
  app/src/main/java/com/example/donotlate/core/data/repository/PromiseRoomRepositoryImpl.kt
  app/src/main/java/com/example/donotlate/core/domain/repository/FirebaseDataRepository.kt
  app/src/main/java/com/example/donotlate/core/domain/repository/PromiseRoomRepository.kt
  app/src/main/java/com/example/donotlate/core/domain/usecase/promiseusecase/RemoveParticipantsUseCase.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/ConsumptionActivity.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/ConsumptionViewModel.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/dialog/ConsumptionConfirmDialog.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/DelayFragment.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/DirectionRouteActivity.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/DirectionsDialogFragment.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/DirectionsViewModel1.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/MapFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/domain/usecase/MessageSendingUseCase.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/domain/usecase/UpdateArrivalStatusUseCase.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonDialog.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonSelectionDialog.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/presentation/detail/PlaceDetailFragment.kt
  app/src/main/res/layout/back_dialog_consumption.xml
  app/src/main/res/layout/fragment_directions_dialog.xml
  app/src/main/res/layout/fragment_my_promise_room.xml
Labels: enhancement, fix

#100 Temp/merge dialog
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/MapFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
Labels: enhancement, fix

#102 Feat/deparure button on off
  .idea/shelf/Uncommitted_changes_before_Update_at_6_25_24,_15_58_[Changes]/shelved.patch
  app/src/main/java/com/example/donotlate/core/data/repository/FirebaseDataSourceImpl.kt
  app/src/main/java/com/example/donotlate/core/domain/repository/FirebaseDataRepository.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/domain/usecase/UpdateDepartureStatusUseCase.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseListFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseListViewModel.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/ViewPagerFragment.kt
  app/src/main/res/drawable/cursor.xml
  app/src/main/res/drawable/cusor_left.xml
  app/src/main/res/drawable/cusor_right.xml
  app/src/main/res/layout/fragment_calculation1.xml
  app/src/main/res/layout/fragment_calculation2.xml
  app/src/main/res/layout/fragment_friends_request.xml
  app/src/main/res/layout/fragment_my_promise_room.xml
  app/src/main/res/layout/fragment_place_search.xml
  app/src/main/res/layout/fragment_room_friend.xml
  app/src/main/res/layout/fragment_room_map.xml
  app/src/main/res/layout/fragment_room_start.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#104 Feature/240625 chat dialog
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RoomExitDialog.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomFriendFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomMapFragment.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/SettingFragment.kt
  app/src/main/java/com/example/donotlate/feature/setting/presentation/view/dialog/WithdrawDialog.kt
  app/src/main/res/layout/dialog_radiobutton_selection.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_request_dialog.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#105 Temp/merge dialog
  app/src/main/java/com/example/donotlate/feature/consumption/data/database/RoomDao.kt
  app/src/main/java/com/example/donotlate/feature/consumption/data/database/RoomDatabase.kt
  app/src/main/java/com/example/donotlate/feature/consumption/data/repository/ConsumptionRepositoryImpl.kt
  app/src/main/java/com/example/donotlate/feature/consumption/presentation/ConsumptionViewModel.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/DirectionsViewModel1.kt
  app/src/main/java/com/example/donotlate/feature/directionRoute/presentation/MapFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/dialog/RadioButtonSelectionDialog.kt
Labels: enhancement, fix

#106 Feat/deparure button on off
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomFragment.kt
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
Labels: enhancement

#107 fix: sdk 33 getParcelable
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomMapBottomFragment.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/view/RoomMapFragment.kt
Labels: fix

#108 Feat/deparure button on off
  app/src/main/java/com/example/donotlate/core/util/util.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/presentation/detail/PlaceDetailFragment.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#109 fix: 소비내역 xml 간격 수정
  app/src/main/java/com/example/donotlate/feature/mypromise/presentation/view/MyPromiseRoomViewModel.kt
  app/src/main/res/layout/item_consumption.xml
Labels: fix

#111 Feature/240625 layout fix
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26__3_43__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher-playstore.png
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher1.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher2.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher3.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher4.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground1.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground2.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground3.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_foreground4.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round1.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round2.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round3.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/ic_launcher_round4.webp
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2024-06-26_오후_3_43_[Changes]/shelved.patch
  app/build.gradle.kts
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/donotlate/feature/directionRoute/data/network/DirectionsApiService.kt
  app/src/main/java/com/example/donotlate/feature/room/presentation/dialog/BackFragmentDialog.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/api/NetWorkClient.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/data/remote/GooglePlacesApiService.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/presentation/adapter/MapAdapter.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/presentation/detail/PlaceDetailFragment.kt
  app/src/main/java/com/example/donotlate/feature/searchPlace/presentation/search/PlaceSearchFragment.kt
  app/src/main/res/layout/fragment_my_promise_room.xml
  app/src/main/res/layout/fragment_mypromise_list.xml
  app/src/main/res/layout/fragment_room_date_dialog.xml
  app/src/main/res/layout/item_rv_my_promise.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#112 Temp/merge dialog
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/back_dialog_consumption.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#118 add manifest 수정, 오전 오후 시간 확인 한번만 부탁드리겠습니다
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nomorelateness/donotlate/feature/directionRoute/presentation/MapFragment.kt
Labels: fix
